Adding GitHub Actions workflow test for duplicate filenames

diff --git a/.github/workflows/yaml-linting.yml b/.github/workflows/yaml-linting.yml
--- a/.github/workflows/yaml-linting.yml
+++ b/.github/workflows/yaml-linting.yml
@@ -16,6 +16,16 @@ jobs:
             for i in $files; do echo "::error file=$i,line=1::Unexpected extension"; done
             exit 1;
           fi
+          unset files
+      - name: Check duplicate file names
+        run: |
+          files=$(find "$GITHUB_WORKSPACE/yml/OSBinaries" "$GITHUB_WORKSPACE/yml/OtherMSBinaries" -type f -printf '%h %f\n' -iname "*.yml" | sort -t ' ' -k 2,2 -f | uniq -i -f 1 --all-repeated=separate | tr ' ' '/')
+          if [[ $files ]]; then
+            echo "Files with duplicate filenames detected, please make sure you don't create duplicate entries.";
+            for i in $files; do echo "::error file=$i,line=1::Duplicate filename"; done
+            exit 1;
+          fi
+          unset files
       - name: yaml-lint
         uses: ibiqlik/action-yamllint@v3
         with:
